Rails.application.config.assets.precompile += %w( template_A.css images/templateA/*.jpg images/templateA/*.png foundation_and_overrides.css )
Rails.application.config.assets.precompile += %w( template_B.css images/templateB/*.jpg images/templateB/*.png)
Rails.application.config.assets.precompile += %w( template_C.css images/templateC/*.jpg images/templateC/*.png)
Rails.application.config.assets.precompile += %w( template_D.css images/templateD/*.jpg images/templateD/*.png)
Rails.application.config.assets.precompile += %w( module.css images/modules/*.jpg images/modules/*.png )