Rails.application.config.assets.precompile += %w( templateA.css images/templateA/*.jpg images/templateA/*.png foundation_and_overrides.css )
Rails.application.config.assets.precompile += %w( templateB.css images/templateB/*.jpg images/templateB/*.png)
Rails.application.config.assets.precompile += %w( templateC.css images/templateC/*.jpg images/templateC/*.png)
Rails.application.config.assets.precompile += %w( templateD.css images/templateD/*.jpg images/templateD/*.png)
Rails.application.config.assets.precompile += %w( module.css images/modules/*.jpg images/modules/*.png )